sudo: required 
dist: trusty 
language: generic
notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
    - ROS_DISTRO="indigo"
    - UPSTREAM_WORKSPACE=file
    - ROSINSTALL_FILENAME=.travis.rosinstall
    - BEFORE_SCRIPT="./.travis.install.sh"
    - ROS_PARALLEL_TEST_JOBS=-j2
    - NOT_TEST_INSTALL=true
  matrix:
    - ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script: travis_wait .ci_config/travis.sh
#  - source ./travis.sh  # Enable this when you have a package-local script 
